const ONLY_MY_CLUSTERS_TOGGLE_CLUSTERS_LIST = 'onlyViewMyClustersToggleClustersList';
const ONLY_MY_CLUSTERS_TOGGLE_CLUSTER_ARCHIVES_LIST = 'onlyViewMyClustersToggleClusterArchivesList';
const ENV_OVERRIDE_LOCALSTORAGE_KEY = 'ocmOverridenEnvironment';
const AWS_ACCOUNT_ROSA_LOCALSTORAGE_KEY = 'rosaAwsAccount';
const HAD_INFLIGHT_ERROR_LOCALSTORAGE_KEY = 'hadInflightErrors';
const RESTRICTED_ENV_OVERRIDE_LOCALSTORAGE_KEY = 'restrictedEnvOverride';
const HAS_USER_DISMISSED_RECOMMENDED_OPERATORS_ALERT = 'hasUserDismissedRecommendedOperatorsAlert';
const FEATURE_GATE_OVERRIDES_KEY = 'featureGateOverrides';

const localStorageConstants = {
  ONLY_MY_CLUSTERS_TOGGLE_CLUSTERS_LIST,
  ONLY_MY_CLUSTERS_TOGGLE_CLUSTER_ARCHIVES_LIST,
  ENV_OVERRIDE_LOCALSTORAGE_KEY,
  AWS_ACCOUNT_ROSA_LOCALSTORAGE_KEY,
  HAD_INFLIGHT_ERROR_LOCALSTORAGE_KEY,
  RESTRICTED_ENV_OVERRIDE_LOCALSTORAGE_KEY,
  HAS_USER_DISMISSED_RECOMMENDED_OPERATORS_ALERT,
  FEATURE_GATE_OVERRIDES_KEY,
};

export {
  ONLY_MY_CLUSTERS_TOGGLE_CLUSTERS_LIST,
  ONLY_MY_CLUSTERS_TOGGLE_CLUSTER_ARCHIVES_LIST,
  ENV_OVERRIDE_LOCALSTORAGE_KEY,
  AWS_ACCOUNT_ROSA_LOCALSTORAGE_KEY,
  HAD_INFLIGHT_ERROR_LOCALSTORAGE_KEY,
  RESTRICTED_ENV_OVERRIDE_LOCALSTORAGE_KEY,
  HAS_USER_DISMISSED_RECOMMENDED_OPERATORS_ALERT,
  FEATURE_GATE_OVERRIDES_KEY,
};
export default localStorageConstants;
